### ISSUE TITLE
from: can't read /var/mail/onvif

### ISSUE THREAD

**Issue by santhku** [FalkTannhaeuser/python-onvif-zeep#51]
When i try to run this command, 

from onvif import ONVIFCamera

Im getting the below error message
from: can't read /var/mail/onvif

How can i resolve this

**Comment by zajc3w** [comment]
Run it in script not in shell. It's python command as far as i know it's importing ONVIFCamera library from onvif library.

**Comment by santhku** [comment]
Thanks Solved...
