### ISSUE TITLE
Security token authentication/authorization error

### ISSUE THREAD

**Issue by canozcivelek** [FalkTannhaeuser/python-onvif-zeep#70]
Hi, I'm trying to access my ONVIF enabled IP camera to perform zoom/focus functions. I can successfully stream from xx.xx.xx.xx:554 with username and pwd. On the web UI, it is stated that the ONVIF port is 8899. I tried with both ports but always ended up in the following error:

**onvif.exceptions.ONVIFError: Unknown error: The security token could not be authenticated or authorized**
What am I missing here? Can the ONVIF credentials be different? If so where could I find them?

Thanks a lot for your time!

**Comment by diogopaschoal-tw** [comment]
Hi, @canozcivelek. How did you fixed it?
I'm getting an error for most of all operations. Maybe my cam do not support most of it.

```
The action requested requires authorization and the sender is not authorized
```
