### ISSUE TITLE
"Unknown fault occured" in creating the camera

### ISSUE THREAD

**Issue by relaxtheo** [FalkTannhaeuser/python-onvif-zeep#92]
I got a exception in calling "ONVIFCamera(ip, port, user, pass)", "Unknown fault occured".

By debugging the client.py, this problem should happened in calling "capabilities = self.devicemgmt.GetCapabilities({'Category': 'All'})"

I have tried 2 cameras, they have same problem. By using OnvifDeviceManager on windows, they work fine.

What could be the problem? Thank you.

**Comment by relaxtheo** [comment]
The problem is caused by the incorrect port, you should get both IP and port in the xaddrs

**Comment by Kerblif** [comment]
@relaxtheo, can you explain in more detail how to solve this problem, please?

**Comment by Kerblif** [comment]
Ok, http port and server port is different things.

In my case: 80 is http port, 6688 is server port. You need pass 6688, not 80.
